alias csio-start="csio-full"
alias cargo-run="cd ~/cybersec-s3-pipeline && cargo run"
alias cr="cargo run"
alias cr="cd ~/cybersec-s3-pipeline && cargo run"
alias cargo-run="cd ~/cybersec-s3-pipeline && cargo run"
