apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: oscp-prod

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns
rules:
- apiGroups: [""]
  resources: ["services","endpoints","pods"]
  verbs: ["*"]
- apiGroups: ["extensions","networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["*"]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: oscp-prod
spec:
  template:
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: k8s.gcr.io/external-dns/external-dns:v0.13.6
        args:
        - --source=ingress
        - --domain-filter=oscp-toolkit.example.com
        - --provider=aws
        env:
        - name: AWS_REGION
          value: "eu-north-1"
